/**
 * Do not edit directly
 * Generated on Thu, 09 Mar 2023 12:49:30 GMT
 */

export default tokens;

declare interface DesignToken {
  value: any;
  name?: string;
  comment?: string;
  themeable?: boolean;
  attributes?: {
    category?: string;
    type?: string;
    item?: string;
    subitem?: string;
    state?: string;
    [key: string]: any;
  };
  [key: string]: any;
}

declare const tokens: {
  "Dark": {
    "Primary": DesignToken,
    "On Primary": DesignToken,
    "Primary Container": DesignToken,
    "On Primary Container": DesignToken,
    "Primary Variant": DesignToken,
    "On Primary Variant": DesignToken,
    "Secondary": DesignToken,
    "On Secondary": DesignToken,
    "Secondary Container": DesignToken,
    "On Secondary Container": DesignToken,
    "Secondary Variant": DesignToken,
    "On Secondary Variant": DesignToken,
    "Success": DesignToken,
    "On Success": DesignToken,
    "Success Container": DesignToken,
    "On Success Container": DesignToken,
    "Alert": DesignToken,
    "On Alert": DesignToken,
    "Alert Container": DesignToken,
    "On Alert Container": DesignToken,
    "Error": DesignToken,
    "On Error": DesignToken,
    "Error Container": DesignToken,
    "On Error Container": DesignToken,
    "Info": DesignToken,
    "On Info": DesignToken,
    "Info Container": DesignToken,
    "On Info Container": DesignToken,
    "Neutral": DesignToken,
    "On Neutral": DesignToken,
    "Neutral Container": DesignToken,
    "On Neutral Container": DesignToken,
    "Background": DesignToken,
    "On Background": DesignToken,
    "Surface": DesignToken,
    "On Surface": DesignToken,
    "Surface Inverse": DesignToken,
    "On Surface Inverse": DesignToken,
    "Outline": DesignToken,
    "Overlay": DesignToken,
    "On Surface Dim 1 (Text)": DesignToken,
    "On Surface Dim 2 (Icon)": DesignToken,
    "On Surface Dim 3 (Disabled)": DesignToken,
    "On Surface Dim 4 (Low Elements)": DesignToken,
    "On Surface Dim 5 (Press & Ripple Surfaces)": DesignToken,
    "Primary Dim 1 (Text)": DesignToken,
    "Primary Dim 2 (Icon)": DesignToken,
    "Primary Dim 3 (Disabled)": DesignToken,
    "Primary Dim 4 (Low Elements)": DesignToken,
    "Primary Dim 5 (Press & Ripple Surfaces)": DesignToken
  },
  "Light": {
    "Primary": DesignToken,
    "On Primary": DesignToken,
    "Primary Container": DesignToken,
    "On Primary Container": DesignToken,
    "Primary Variant": DesignToken,
    "On Primary Variant": DesignToken,
    "Secondary": DesignToken,
    "On Secondary": DesignToken,
    "Secondary Container": DesignToken,
    "On Secondary Container": DesignToken,
    "Secondary Variant": DesignToken,
    "On Secondary Variant": DesignToken,
    "Success": DesignToken,
    "On Success": DesignToken,
    "Success Container": DesignToken,
    "On Success Container": DesignToken,
    "Alert": DesignToken,
    "On Alert": DesignToken,
    "Alert Container": DesignToken,
    "On Alert Container": DesignToken,
    "Error": DesignToken,
    "On Error": DesignToken,
    "Error Container": DesignToken,
    "On Error Container": DesignToken,
    "Info": DesignToken,
    "On Info": DesignToken,
    "Info Container": DesignToken,
    "On Info Container": DesignToken,
    "Neutral": DesignToken,
    "On Neutral": DesignToken,
    "Neutral Container": DesignToken,
    "On Neutral Container": DesignToken,
    "Background": DesignToken,
    "On Background": DesignToken,
    "Surface": DesignToken,
    "On Surface": DesignToken,
    "Surface Inverse": DesignToken,
    "On Surface Inverse": DesignToken,
    "Outline": DesignToken,
    "Overlay": DesignToken,
    "On Surface Dim 1 (Text)": DesignToken,
    "On Surface Dim 2 (Icon)": DesignToken,
    "On Surface Dim 3 (Disabled)": DesignToken,
    "On Surface Dim 4 (Low Elements)": DesignToken,
    "On Surface Dim 5 (Press & Ripple Surfaces)": DesignToken,
    "Primary Dim 1 (Text)": DesignToken,
    "Primary Dim 2 (Icon)": DesignToken,
    "Primary Dim 3 (Disabled)": DesignToken,
    "Primary Dim 4 (Low Elements)": DesignToken,
    "Primary Dim 5 (Press & Ripple Surface)": DesignToken
  },
  "Brand": {
    "TheBlue 50": DesignToken,
    "TheBlue 100": DesignToken,
    "TheBlue 200": DesignToken,
    "TheBlue 300": DesignToken,
    "TheBlue 400": DesignToken,
    "TheBlue 500": DesignToken,
    "TheBlue 600": DesignToken,
    "TheBlue 700": DesignToken,
    "TheBlue 800": DesignToken,
    "TheBlue 900": DesignToken,
    "TheBlue V": DesignToken,
    "Sugarcotton 50": DesignToken,
    "Sugarcotton 100": DesignToken,
    "Sugarcotton 200": DesignToken,
    "Sugarcotton 300": DesignToken,
    "Sugarcotton 400": DesignToken,
    "Sugarcotton 500": DesignToken,
    "Sugarcotton 600": DesignToken,
    "Sugarcotton 700": DesignToken,
    "Sugarcotton 800": DesignToken,
    "Sugarcotton 900": DesignToken,
    "Apple 50": DesignToken,
    "Apple 100": DesignToken,
    "Apple 200": DesignToken,
    "Apple 300": DesignToken,
    "Apple 400": DesignToken,
    "Apple 500": DesignToken,
    "Apple 600": DesignToken,
    "Apple 700": DesignToken,
    "Apple 800": DesignToken,
    "Apple 900": DesignToken,
    "Wiggins 50": DesignToken,
    "Wiggins 100": DesignToken,
    "Wiggins 200": DesignToken,
    "Wiggins 300": DesignToken,
    "Wiggins 400": DesignToken,
    "Wiggins 500": DesignToken,
    "Wiggins 600": DesignToken,
    "Wiggins 700": DesignToken,
    "Wiggins 800": DesignToken,
    "Wiggins 900": DesignToken,
    "Chili 50": DesignToken,
    "Chili 100": DesignToken,
    "Chili 200": DesignToken,
    "Chili 300": DesignToken,
    "Chili 400": DesignToken,
    "Chili 500": DesignToken,
    "Chili 600": DesignToken,
    "Chili 700": DesignToken,
    "Chili 800": DesignToken,
    "Chili 900": DesignToken,
    "Sky 50": DesignToken,
    "Sky 100": DesignToken,
    "Sky 200": DesignToken,
    "Sky 300": DesignToken,
    "Sky 400": DesignToken,
    "Sky 500": DesignToken,
    "Sky 600": DesignToken,
    "Sky 700": DesignToken,
    "Sky 800": DesignToken,
    "Sky 900": DesignToken,
    "Surfer 50": DesignToken,
    "Surfer 100": DesignToken,
    "Surfer 200": DesignToken,
    "Surfer 300": DesignToken,
    "Surfer 400": DesignToken,
    "Surfer 500": DesignToken,
    "Surfer 600": DesignToken,
    "Surfer 700": DesignToken,
    "Surfer 800": DesignToken,
    "Surfer 900": DesignToken,
    "Kiwi 50": DesignToken,
    "Kiwi 100": DesignToken,
    "Kiwi 200": DesignToken,
    "Kiwi 300": DesignToken,
    "Kiwi 400": DesignToken,
    "Kiwi 500": DesignToken,
    "Kiwi 600": DesignToken,
    "Kiwi 700": DesignToken,
    "Kiwi 800": DesignToken,
    "Kiwi 900": DesignToken,
    "Black": DesignToken,
    "White": DesignToken,
    "Facebook": DesignToken,
    "Twitter": DesignToken
  },
  "tokenSetOrder": {
    "0": DesignToken,
    "1": DesignToken,
    "2": DesignToken
  }
}