name: "Taskbox Deployment"
on:
  push:
    branches:
      - "main"
    paths:
      - "taskbox/**/*"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: taskbox
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.TASKBOX_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: taskbox
